spring:
  application:
    name: ws-tg-ui
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres_local
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: ws-tg-ui
    show-sql: false
  flyway:
    enabled: true
    schemas: ws-tg-ui
    baseline-on-migrate: true
    out-of-order: true
    locations: classpath:db/migration
    baseline-version: 1

server:
  port: 18767
  servlet:
    encoding:
      force: true
      charset: UTF-8

ORDER_GATEWAY_URL: ${GATEWAY_URL:http://localhost:18889}

auth:
  rest:
    authUrl: ${ORDER_GATEWAY_URL}/ws-auth/v1/workers/auth/login
    username: ${AUTH_USERNAME}
    password: ${AUTH_PASSWORD}

feign:
  ws-auth:
    url: ${ORDER_GATEWAY_URL}
  ws-order:
    order:
      url: ${ORDER_GATEWAY_URL}/ws-order/v1/order/customer
    bid:
      url: ${ORDER_GATEWAY_URL}/ws-order/v1/bid
    feedback:
      url: ${ORDER_GATEWAY_URL}/ws-order/v1/feedback


jwt:
  public:
    key: ${JWT_PUBLIC_SECRET_KEY}
  access-token:
    expiration: 3600000
  refresh-token:
    expiration: 36000000

order-service:
  executor:
    core-pool-size: 10
    max-pool-size: 20
    queue-capacity: 100
  scheduler:
    fixed-rate: 3600000

bot:
  name: ICQMasterBot
  token: 7619871226:AAH_FVOnzzaOsY8tiiu_nHrcPbgIJNKSQXs
  command-list:
    '/start': "Начать работу"
    '/create_order': "Создать заказ"
    '/my_active_order': "Мои активные заказы"
    '/my_archive_order': "Заказы в архиве"